import json
from pathlib import Path
from typing import Any, Dict, Iterator, Tuple

import pytest

from q_block.atom import Atom
from q_block.atoms_data import (ATOMS_SYMBOLS_SYMBOL_TO_Z,
                                ATOMS_SYMBOLS_Z_TO_SYMBOL)
from q_block.basis_set_pople import parse_gaussian_basis
from q_block.electron import Shell, SpinOrbital
from tests.verification_data.expected_atom_pure import EXPECTED_ATOM_PURE

SpinKey = Tuple[int, int, int, float]
SpinMap = Dict[SpinKey, bool]

BASIS_ROOT: Path = Path("./data/basis_set/gto_gaussian_format")
GOLDEN_ROOT: Path = Path("./tests/verification_data/gto_population")

BASIS_FILES = [
    "3-21G.gbs",
    "6-31G.gbs",
    "6-311G.gbs",
    "6-311++Gss.gbs",
]


def extract_spin_map(atom: Atom) -> SpinMap:
    """
    Extract the complete spin-orbital occupancy map from an Atom instance.

    :param atom: a fully initialized & filled Atom object
    :returns: mapping of spin orbitals to occupied flags
    """
    result: SpinMap = {}

    shells: Dict[int, Shell] = atom.shells
    for shell in shells.values():
        for subs in shell.subshells:
            for orb in subs.orbitals:
                up: SpinOrbital = orb.spin_up
                down: SpinOrbital = orb.spin_down

                result[(orb.n, orb.l, orb.m, up.s)] = up.occupied
                result[(orb.n, orb.l, orb.m, down.s)] = down.occupied

    return result


def count_spin_map(spin_map: SpinMap) -> int:
    """
    Count number of electrons in a spin-orbital map.

    :param spin_map: spin-orbital occupancy
    :returns: number of occupied spin orbitals
    """
    return sum(1 for occupied in spin_map.values() if occupied)


def maps_equal(a: SpinMap, b: SpinMap) -> bool:
    """
    Compare two spin-orbital maps for exact match of keys and values.
    """
    if set(a.keys()) != set(b.keys()):
        return False
    for k in a:
        if a[k] != b[k]:
            return False
    return True


@pytest.mark.parametrize("atomic_number", range(1, 119))
def test_atom_pure_matches_expected(
    atomic_number: int,
) -> None:
    """
    Test that Atom(atomic_number, pure mode) matches the expected static spin map.

    :param atomic_number: atomic number under test
    """
    expected_pure: SpinMap = EXPECTED_ATOM_PURE[atomic_number]

    atom = Atom(
        atomic_number=atomic_number,
        maximal_principal_quantum_number=7,
        empirical_exceptions=None,
    )
    atom.fill_occupancy()

    actual = extract_spin_map(atom)

    assert set(actual.keys()) == set(
        expected_pure.keys()
    ), f"Spin-orbital key mismatch for atomic_number={atomic_number}"

    for key in actual:
        assert (
            actual[key] == expected_pure[key]
        ), f"Value mismatch at atomic_number={atomic_number} on spin orbital {key}"

    assert (
        count_spin_map(actual) == atomic_number
    ), f"Electron count mismatch for atomic_number={atomic_number}"


@pytest.mark.parametrize("atomic_number", range(1, 119))
def test_atom_pure_matches_expected_for_exceptions(
    atomic_number: int,
) -> None:
    """
    Test that Atom(atomic_number, pure mode) matches the expected pure spin-orbital map,
    but **only for atoms that have empirical exceptions**.

    Meaning:
      - atomic_number is tested only if it appears in EXPECTED_ATOM_EMPIRICAL
      - For other atomic_number, this test is skipped

    :param atomic_number: atomic number under test
    """
    # Only test atoms that actually have empirical exceptions
    # if atomic_number not in EXPECTED_ATOM_EMPIRICAL:
    #     pytest.skip(f"atomic_number={atomic_number} has no empirical exception — skipping pure test.")

    expected_pure: SpinMap = EXPECTED_ATOM_PURE[atomic_number]

    atom = Atom(
        atomic_number=atomic_number,
        maximal_principal_quantum_number=7,
        empirical_exceptions=None,
    )
    atom.fill_occupancy()

    # Ensure the atom's state is correctly updated without relying on a return value
    actual = extract_spin_map(atom)

    # Keyset must match exactly
    assert set(actual.keys()) == set(
        expected_pure.keys()
    ), f"[PURE] Spin-orbital key mismatch for exception atom atomic_number={atomic_number}"

    # Values must match exactly
    for key in actual:
        assert (
            actual[key] == expected_pure[key]
        ), f"[PURE] Value mismatch at atomic_number={atomic_number} on spin orbital {key}"

    # Pure electron count must always equal atomic_number
    assert (
        count_spin_map(actual) == atomic_number
    ), f"[PURE] Electron count mismatch for atomic_number={atomic_number}"


"""
Golden-reference tests for GTO population.

===============================================================================
PURPOSE
===============================================================================

This test module verifies the correctness of:

    Atom.populate_spinorbitals_with_gto

by comparing its output against *golden-reference data* generated by:

    tools/generate_golden.py

Each golden-reference file corresponds to ONE basis set and contains
verified GTO assignments for ALL atoms defined in that basis.

Each (basis set, atom) pair is tested as an independent unit test.
===============================================================================
"""


def _serialize_atom_for_test(
    atom: Atom,
    basis_name: str,
) -> Dict[str, Any]:
    """Serialize Atom into golden-reference comparable structure."""

    orbitals: Dict[str, Dict[str, list]] = {}

    for shell in atom.shells.values():
        for subshell in shell.subshells:

            occupied_spinorbitals = [
                so
                for orb in subshell.orbitals
                for so in (orb.spin_up, orb.spin_down)
                if so.occupied
            ]

            if not occupied_spinorbitals:
                continue

            key = f"{subshell.n}{'spdf'[subshell.l]}"
            so = occupied_spinorbitals[0]

            orbitals[key] = {
                "exponents": so.data["exponents"],
                "contractions": so.data["contractions"],
            }

    return {
        "symbol": ATOMS_SYMBOLS_Z_TO_SYMBOL[atom.atomic_number],
        "Z": atom.atomic_number,
        "basis": basis_name,
        "orbitals": orbitals,
    }


def _iter_golden_test_cases() -> Iterator[Tuple[str, str]]:
    """
    Generate (basis_file, atom_symbol) pairs for pytest parametrization.

    Yields
    ------
    (basis_file, atom_symbol)
        One test case per atom per basis set.
    """

    for basis_file in BASIS_FILES:
        basis_name = Path(basis_file).stem
        golden_path = GOLDEN_ROOT / f"{basis_name}.json"

        with golden_path.open() as f:
            golden = json.load(f)

        for symbol in golden["atoms"]:
            yield basis_file, symbol


@pytest.mark.parametrize(
    "basis_file, symbol",
    list(_iter_golden_test_cases()),
    ids=lambda p: p if isinstance(p, str) else None,
)
def test_golden_gto_population(
    basis_file: str,
    symbol: str,
) -> None:
    """
    Verify GTO population for a single atom in a single basis set.

    This test compares the populated GTO data against manually verified
    golden-reference data.

    :param basis_file: Gaussian basis set filename.
    :type basis_file: str

    :param symbol: Atomic symbol (e.g. ``"H"``, ``"C"``, ``"Fe"``).
    :type symbol: str
    """

    basis_path = BASIS_ROOT / basis_file
    basis_name = basis_path.stem

    golden_path = GOLDEN_ROOT / f"{basis_name}.json"
    with golden_path.open() as f:
        golden = json.load(f)

    basis = parse_gaussian_basis(filepath=str(basis_path))
    golden_atom = golden["atoms"][symbol]

    atom = Atom(
        atomic_number=ATOMS_SYMBOLS_SYMBOL_TO_Z[symbol],
        basis_set=basis[symbol],
    )
    atom.populate_spinorbitals_with_gto()

    snapshot = _serialize_atom_for_test(
        atom=atom,
        basis_name=basis_name,
    )

    assert snapshot == golden_atom, (
        f"GTO population mismatch for atom {symbol} " f"in basis {basis_name}"
    )
