@startuml bdd_models

package "models" {
  class SpinOrbital
  class Orbital
  class SubShell
  class Shell
  class Atom
}

' ═══ Composition ═══

Orbital *-- "2" SpinOrbital
SubShell *-- "1..*" Orbital
Shell *-- "1..*" SubShell
Atom *-- "1..*" Shell

@enduml
